/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_ui;

import conexion_mysql.conexionMySQL;
import conexion_mysql.servicios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marco
 */
public class Mensualidades extends javax.swing.JInternalFrame {

    public static String v;
    Calendar Fecha_actual = new GregorianCalendar();
    PreparedStatement ps;
    ResultSet rs;

    /**
     * Creates new form Mensualidades
     */
    public Mensualidades() {
        initComponents();
        int x = frm_mAdmin.escritorio.getWidth() - this.getWidth();
        int y = frm_mAdmin.escritorio.getHeight() - this.getHeight();
        setLocation(x / 2, y / 2);
        setVisible(true);
        v = "v";
        TxtFecha.setEnabled(false);
        TxtFecha.setCalendar(Fecha_actual);
    }
    public void vencimiento_fecha(){
        
    }
    public void insertar_abono() {
        try {
            Connection con = conexionMySQL.getConnection();
            ps = con.prepareStatement("INSERT INTO abonos (`referencia_a`, `servicio`, `fecha`, `abono`, `nota`) VALUES (?, ?, ?, ?, ?);");
            ps.setString(1, txtreferencia.getText());
            ps.setString(2, txtservicio.getText());
            ps.setString(3, ((JTextField) TxtFecha.getDateEditor().getUiComponent()).getText());
            ps.setString(4, txtabono.getText());
            ps.setString(5, txtnotas.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                slect_spagos();
                JOptionPane.showMessageDialog(null, "Se realizo el pago de manera correcta");
            } else {
                JOptionPane.showMessageDialog(null, "El pago no se realizo");
            }
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "Error del pago");
        }
    }

    private void slect_spagos() {
        String Costo = null;
        String Anticipo = null;
        try {
            Connection con = conexionMySQL.getConnection();
            ps = con.prepareStatement("SELECT costo, anticipo FROM s_pagos where referencia_p  = ?;");
            ps.setString(1, txtreferencia.getText());
            rs = ps.executeQuery();
            while (rs.next()) {
                Costo = rs.getString("costo");
                Anticipo = rs.getString("anticipo");
         
            }
            if (Costo.equals(Anticipo)) {
                Connection myConn = conexionMySQL.getConnection();
                ps = myConn.prepareStatement("UPDATE pagos SET estatus = 'pagado' WHERE referencia = ?;");
                ps.setString(1, txtreferencia.getText());
                ps.executeUpdate();
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }
    private void limpiar() {
        DefaultTableModel modelo = new DefaultTableModel();
        jTable1.setModel(modelo);
        modelo.setRowCount(0);
        TxtClaveUsuario.setText(null);
        txtreferencia.setText(null);
        txtservicio.setText(null);
        txtabono.setText(null);
        txtnotas.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtreferencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtservicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtabono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnotas = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtClaveUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtSaldoUser = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Mensualidades");
        setPreferredSize(new java.awt.Dimension(760, 470));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setBackground(new java.awt.Color(69, 73, 74));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Datos de deudor");

        txtreferencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtreferencia.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtreferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreferenciaActionPerformed(evt);
            }
        });
        txtreferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtreferenciaKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(69, 73, 74));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Referencia pago");

        txtservicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtservicio.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtservicioActionPerformed(evt);
            }
        });
        txtservicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtservicioKeyTyped(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(69, 73, 74));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Servicio");

        txtabono.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtabono.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtabono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabonoActionPerformed(evt);
            }
        });
        txtabono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtabonoKeyTyped(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(69, 73, 74));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Monto a pagar");

        jLabel7.setBackground(new java.awt.Color(69, 73, 74));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Nota");

        txtnotas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnotas.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnotasActionPerformed(evt);
            }
        });
        txtnotas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnotasKeyTyped(evt);
            }
        });

        jButton3.setText("Abonar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtabono, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtabono, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtreferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtservicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(txtnotas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        TxtClaveUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtClaveUsuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        TxtClaveUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtClaveUsuarioCaretUpdate(evt);
            }
        });
        TxtClaveUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtClaveUsuarioActionPerformed(evt);
            }
        });
        TxtClaveUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtClaveUsuarioKeyTyped(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(69, 73, 74));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Nombre del alumno");

        TxtFecha.setBackground(new java.awt.Color(255, 255, 255));
        TxtFecha.setForeground(new java.awt.Color(255, 255, 255));
        TxtFecha.setDateFormatString("yyyy/MM/dd");
        TxtFecha.setInheritsPopupMenu(true);

        jLabel1.setText("Saldo:");

        txtSaldoUser.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtClaveUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))))
                .addGap(10, 10, 10)
                .addComponent(txtSaldoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSaldoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        v = null;

    }//GEN-LAST:event_formInternalFrameClosing

    private void txtreferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreferenciaActionPerformed

    private void txtreferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtreferenciaKeyTyped
        char tecla = evt.getKeyChar();
        if (((tecla < '0') || (tecla > '9'))) {
            evt.consume();
        }
        if (txtreferencia.getText().length() >= 5) {
            evt.consume();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtreferenciaKeyTyped

    private void TxtClaveUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtClaveUsuarioActionPerformed

    }//GEN-LAST:event_TxtClaveUsuarioActionPerformed

    private void TxtClaveUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtClaveUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtClaveUsuarioKeyTyped

    private void txtservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtservicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtservicioActionPerformed

    private void txtservicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtservicioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtservicioKeyTyped

    private void txtnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotasActionPerformed

    private void txtnotasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnotasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnotasKeyTyped

    private void txtabonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabonoActionPerformed

    private void txtabonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtabonoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabonoKeyTyped

    private void TxtClaveUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtClaveUsuarioCaretUpdate
        String valor = TxtClaveUsuario.getText();
        if (valor.isEmpty()) {

        } else {
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Referencia");
            modelo.addColumn("Alumno");
            modelo.addColumn("Servicio");
            modelo.addColumn("Saldo");
            modelo.addColumn("Mensualidad");
            String[] datos = new String[5];
            try {
                Connection con = conexionMySQL.getConnection();
                ps = con.prepareStatement("select pagos.referencia,alumno.nombre, servicios.Nombre,(s_pagos.costo - s_pagos.anticipo) as Saldo, \n"
                        + "replace(FORMAT((s_pagos.costo - s_pagos.anticipo)/s_pagos.mensualidad, 2),\",\",\"\") as Mensualidad, alumno.saldo from pagos inner join  s_pagos, alumno, servicios where "
                        + "(pagos.clave_alum = alumno.clave and s_pagos.referencia_p = pagos.referencia and s_pagos.referencia_s = servicios.referencia) and "
                        + "alumno.nombre like '" + valor + "%' and pagos.estatus = 'pendiente';");
                rs = ps.executeQuery();
                while (rs.next()) {
                    jTable1.setModel(modelo);
                    datos[0] = rs.getString(1);
                    datos[1] = rs.getString(2);
                    datos[2] = rs.getString(3);
                    datos[3] = rs.getString(4);
                    datos[4] = rs.getString(5);
                    txtSaldoUser.setText(rs.getString(6));
                    modelo.addRow(datos);
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        }

    }//GEN-LAST:event_TxtClaveUsuarioCaretUpdate

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
        } else {
            txtreferencia.setText(jTable1.getValueAt(fila, 0).toString());
            TxtClaveUsuario.setText(jTable1.getValueAt(fila, 1).toString());
            txtservicio.setText(jTable1.getValueAt(fila, 2).toString());
            txtabono.setText(jTable1.getValueAt(fila, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Connection myConn = conexionMySQL.getConnection();
            ps = myConn.prepareStatement("UPDATE s_pagos SET costo = replace(costo,\",\",\".\") - ?, mensualidad = mensualidad - 1 WHERE referencia_p = ?;");
            ps.setString(1, txtabono.getText());
            ps.setString(2, txtreferencia.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                insertar_abono();
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "Los datos no se aguardaron de manera correcta");
                limpiar();
            }
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtClaveUsuario;
    private com.toedter.calendar.JDateChooser TxtFecha;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSaldoUser;
    private javax.swing.JTextField txtabono;
    private javax.swing.JTextField txtnotas;
    private javax.swing.JTextField txtreferencia;
    private javax.swing.JTextField txtservicio;
    // End of variables declaration//GEN-END:variables
}
